# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
# QuestionsList.create([{ question: '자기소개를 한 번 해보라.' }, { question: '당사 지원동기는 무엇인가?' }, { question: '사람이랑 어울리는 것을 좋아하는 것 같은데 실제로는 어떠한가?' }, { question: '다른 회사는 어디 지원하였고 결과는 어떠한가?' }, { question: '마지막으로 하고싶은 말이 있는가?' }, { question: '입사 후에 어떠한 일을 할 것이고 원하는 부서는 어디인가?' }, { question: '지방으로 근무할 수 있겠는가?' }, { question: '해당 직무를 지원한 동기는 무엇인가?' }, { question: '우리 회사에 대해 아는대로 말해보라.' }, { question: '자신의 취미를 말해보라.' }])
QuestionsList.create([{ question: '자기소개를 해보라.' },
{ question: '당사 지원동기는?' },
{ question: '사람이랑 어울리는 거 좋아하는 것 같은데?' },
{ question: '다른회사는 어디 지원했는가? 결과는?' },
{ question: '마지막으로 하고싶은 말은?' },
{ question: '입사후 어떤 일을 하고 싶은가? / 희망부서는?' },
{ question: '지방근무 가능한가?' },
{ question: '직무지원동기는?' },
{ question: '당사에 대해 아는대로 말해보라.' },
{ question: '자신의 취미를 말해보라.' },
{ question: '주량은 어떻게 되는가?' },
{ question: '가족소개를 해보라.' },
{ question: '전공을 선택한 이유는?' },
{ question: '입사후 포부를 말해보라.' },
{ question: '자신의 장점(강점)은?' },
{ question: '무역을 복수전공했는데, 우리나라 GDP는? 우리나라 수출규모는?' },
{ question: '자신의 특기를 설명해보라.' },
{ question: '동아리활동을 말해보라.' },
{ question: '희망치 않는 업무를 하게된다면? / 다른 일할 마음없는가?' },
{ question: '학점이 높지 않은데, 왜 그렇다고 생각하나?' },
{ question: '졸업후 지금까지 뭐했나?' },
{ question: '자신의 장단점을 말해보라.' },
{ question: '귀하를 채용해야하는 이유는?' },
{ question: '지원한 분야에서 어떤 일을 하는지 아는가?' },
{ question: '아르바이트 경험을 말해보라.' },
{ question: '아버님 소개해보라.' },
{ question: '영어로 자기소개' },
{ question: '최근 감명깊게 읽은 책은?' },
{ question: '10년후 자신의 모습을 말해보라.' },
{ question: '무역학을 복수전공한 이유는?' },
{ question: '왜 해외로 교환학생 갔나? 그곳에서 뭘 배웠나?' },
{ question: '당사 이미지는 어떠한가?' },
{ question: '당사 제품 / 상품을 아는대로 설명해보라' },
{ question: '공백기간동안 뭐했는가?(휴학,재수 등)' },
{ question: '자신의 봉사활동에 대해 말해보라.' },
{ question: '멕시코에 봉사활동 갔다고 했는데 왜 멕시코에 갔나? 가서 뭐했고 뭘 배웠나? 멕시코 경제 규모가 어떻게 되나?' },
{ question: '구매란 무엇이라고 생각하는가?' },
{ question: '자신만의 경쟁력 / 최고라고 생각하는 것은?' },
{ question: '존경하는 인물은? 왜? 거기 가게 가봤나?' },
{ question: '지원분야에서 자신의 강점은?' },
{ question: '전공을 소개해보라.' },
{ question: '오스트리아에서 교환학생 했는데 독일어 할 줄아나? 다른 나라 음식 많이 먹어봤나? 기억에 남는 것 있나?' },
{ question: '자신의 꿈은 무엇인가?' },
{ question: '자신의 성격은 어떠한가?' },
{ question: '이성친구 있는가?' },
{ question: '외환관리사 자격증 있는데 이게 뭐지? 왜땄나? 금융권 준비한 거 아닌가?' },
{ question: '와인소믈리에 자격증은 뭐지? 왜땄나? 추천해 줄만한 거 있나? 업무에 어떻게 활용할건가?' },
{ question: '바꾸고 싶은 자신의 단점은?' },
{ question: '일이 힘든 분야인데 해낼 수있겠는가?' },
{ question: '전공이 회사에 어떻게 도움되나?' },
{ question: '좋아하는 운동은?' },
{ question: '부모님 소개해보라.' },
{ question: '구매 담당자가 갖추어야 하는 역량은?' },
{ question: '프로젝트 경험을 말해보라.' },
{ question: '상사와 계속 갈등이 생긴다면?' },
{ question: '자신의 영어실력은 어느 정도라고 생각하는가?' },
{ question: '인생에서 중히 여기는 것은?' },
{ question: '당사의 장단점은?' },
{ question: '당사 업종 지원동기는?' },
{ question: '여러 활동들이 기획활동을 많이 한 것 같은데 왜 구매에 지원했나?' },
{ question: '지원분야와 전공과의 연관성은? / 어떻게 도움되나?' },
{ question: '기억에 남거나 관심있게 들었던 과목은?' },
{ question: '신문보나? 최근 인상깊은 뉴스 / 기사는? 오늘아침 뉴스 봤나?' },
{ question: '생활신조. 좌우명은?' },
{ question: '입사하면 무엇을 기여할 수있는가?' },
{ question: 'FTA에 대한 견해는? / 장단점은?' },
{ question: '성취감을 맛본 경험을 말해보라.' },
{ question: '주위 에서 자신을 어떻게 평가하나?' },
{ question: '스트레스는 어떻게 푸는가?' },
{ question: '희망연봉을 말해보라.' },
{ question: '토익점수가 왜 이리 낮은가?' },
{ question: '상사가 부당한 지시를 내린다면?' },
{ question: '가장 좋아하는 전공과목은? / 이유는?' },
{ question: '당사와 경쟁사의 차이(장단점)를 말해보라.' },
{ question: '전공 선택사유는?' },
{ question: '희망근무지역 선택사유는?' },
{ question: '중요한 약속일에 회사일을 해야 된다면?' },
{ question: '담배 피우는가?(흡연 여부)' },
{ question: '학교생활은 어떠했나?' },
{ question: '전공이 업종과 맞지 않은데 지원한 이유는?' },
{ question: '지원한 분야를 위해 준비한 것은?' },
{ question: '자신의 별명을 말해보라.' },
{ question: '당사에 대해 궁금한 것 없나? / 질문해보라.' },
{ question: '우리회사가 무슨 일을 하는 회사인지 아는가?' },
{ question: '해외경험에서 느낀점 / 배운 것은?' },
{ question: '지원한 분야가 자신과 잘맞다고 생각하는가? / 이유는?' },
{ question: '5년후 자신의 모습은?' },
{ question: '창의력을 발휘한 경험은?' },
{ question: '당사 입사를 위해 준비한 것은?' },
{ question: '편입한 이유는?' },
{ question: '자신의 논문에 대해 말해보라.' },
{ question: '학창시절 기억에 남는 것은?' },
{ question: '[영업] 영업을 잘할려면?' },
{ question: '직장회사 선택기준은?' },
{ question: '휴학한 이유는?' },
{ question: '자신의 대인관계는 어떠한가?' },
{ question: '당사 영업점(대리점 지점 점포)에 가본 적 있는가?' },
{ question: '상사와 의견이 다를 때 어떻게 하겠는가?' },
{ question: '[증권] 주식투자 해봤는가?' },
{ question: '당사를 알게된 계기는?' },
{ question: '당사 제품 / 당사 서비스 이용해본 적 있나?' },
{ question: '당사 홈페이지에 대한 느낌은?' },
{ question: '회사에 몇년까지 일할 생각인가?' },
{ question: '주말에 주로 뭐하는가?' },
{ question: '사람들과 갈등한 경험은? / 어떻게 해결했나?' },
{ question: '당사 면접을 위해 준비한 것은?' },
{ question: '직장생활에서 중요한 것은?' },
{ question: '당사 업종전망과 나아가야할 방향은?' },
{ question: '[영업금융] 자신만의 영업전략은?' },
{ question: '친구 많은가?' },
{ question: '회사위상과 전망은?' },
{ question: '자신의 경력에 대해 말해보라' },
{ question: '최근에 본 영화는?' },
{ question: '영어공부는 어떻게 했는가?' },
{ question: '교외활동을 말해보라. / 공부외에 몰두한 것은?' },
{ question: '리더경험있는가?' },
{ question: '자신의 학교소개' },
{ question: '이번 면접에서 불합격된다면?' },
{ question: '집이 먼데 회사에 어떻게 출근할 것인가?' },
{ question: '자신의 직업관을 말해보라.' },
{ question: '당사 광고 본 적 있나 / 기억에 남는 것은?' },
{ question: '면접관이라면 무엇을 물어보겠는가?' },
{ question: '[여성] 힘든 일 밤샘 가능한가?' },
{ question: '[영업금융] 면접관에게 상품을 팔아보라.' },
{ question: '희망치 않는 지역에 배치된다면?' },
{ question: '지원분야 관련경험있는가?' },
{ question: '해외근무 가능한가?' },
{ question: '최근 사회이슈와 자신의 견해를 말해보라.' },
{ question: '북핵문제에 대한 견해는?' },
{ question: '왜 직장을 구하려 하는가?' },
{ question: '살면서 가장 기뻤던 일, 슬펐던 일은?' },
{ question: '당사와 동종업계 회사를 비교설명해보라.' },
{ question: '당사에 아는사람있는가?' },
{ question: '희망근무지는?' },
{ question: '가장 자랑스러웠거나 잘한 일은?' },
{ question: '[마케팅] 마케팅이란?' },
{ question: '입사가능한 일자는?' },
{ question: '지원분야를 어떻게 잘할 수 있겠는가?' },
{ question: '종교있는가?' },
{ question: '열역학법칙을 설명해보라.' },
{ question: '나이가 많은데 어떻게 극복할 생각인가?' },
{ question: '면접경험있는가? / 이번이 몇번째인가?' },
{ question: '입사하면 어떤 일을 잘할 수 있겠나?' },
{ question: '준비해온 말 있으면 해보라.' },
{ question: '회사일때문에 종교활동을 못한다면?' },
{ question: '자신이 이루고 싶은 목표는?' },
{ question: '당사 주식이 얼마인지 아는가?' },
{ question: '지원한 분야에서 중요한 것은 무엇인가?' },
{ question: '주위 사람 중 당사업종에 종사하는 분있는가?' },
{ question: '컴퓨터활용 능력은?' },
{ question: '부동산 정책 / 부동산 폭등에 대한 견해는?' },
{ question: '복수전공을 한 이유는?' },
{ question: '학점이 아주 좋은데 공부만 하였나? / 비법은?' },
{ question: '실패경험을 말해보라.' },
{ question: '자신있는 외국어로 자기소개' },
{ question: '계속 야근을 해야한다면?' },
{ question: '휴일근무 가능한가?' },
{ question: '기업의 사회적 책임이란? / 왜 해야하는가?' },
{ question: '좋아하는 사람과 싫어하는 사람의 유형은?' },
{ question: '해외경험 왜 했나?' },
{ question: '경제 성장과 분배에 대한 견해는?' },
{ question: '가장 후회하는 일은?' },
{ question: '성격에 대한 주위 사람들의 평은?' },
{ question: '성공경험을 말해보세요.' },
{ question: '직장인으로서의 필요역량은?' },
{ question: '6시그마란? / 왜 중요한가?' },
{ question: '영어로 지원동기를 말해보라' },
{ question: '원칙을 중요시 한다고 했는데 예를 들어보라' },
{ question: '베르누이 정리를 설명해보라' },
{ question: '리더십을 발휘한 경험을 말해보라' },
{ question: '지원분야 관련자격증 있는가?' },
{ question: '당사 업종에 필요한 역량은? / 필요한 자세는?' },
{ question: '영어 외 가능한 외국어는?' },
{ question: '가장 기억에 남는 일은?' },
{ question: '어떤 분야에 열정을 가지고 해본 일은?' },
{ question: '결혼은 언제할 생각인가?' },
{ question: '전직장 연봉은 얼마인가?' },
{ question: '리더십이 무엇이라 생각하나?' },
{ question: '스카웃제의가 들어온다면?' },
{ question: '청년실업 문제에 대한 견해는?' },
{ question: '자신의 학점을 어떻게 생각하는가?' },
{ question: '자기계발을 위해 어떤 노력을 하고 있습니까?' },
{ question: '신문은 어느 면부터 읽나요?' },
{ question: '자신의 경험 / 경력이 회사에 어떻게 도움되나?' },
{ question: '왜 공익 / 방위 출신인가?' },
{ question: '전공어로 자기소개' },
{ question: '첫월급타면 뭐할건가?' },
{ question: '[재지원자] 전에 떨어졌는데 또 지원한 이유는?' },
{ question: '자신이 CEO라면 회사를 어떻게 이끌어 가겠는가?' },
{ question: '팀동료와 갈등이 생긴다면?' },
{ question: '신문 보는 것 있나? / 구독신문은?' },
{ question: '삼성특검에 대한 견해는?' },
{ question: '[여성] 결혼후 직장생활 어떻게할 생각인가?' },
{ question: '감명깊게 본 영화는?' },
{ question: 'ERP 설명' },
{ question: '학생과 직장인의 차이는?' },
{ question: '직장과 가정에 위 급한 일이 겹쳤다면?' },
{ question: '당사업종에 대해 아는대로 말해보라.' },
{ question: '지원한 분야가 적성에 안맞는다면 어떻게 할 것인가?' },
{ question: '[제약영업] 타업종 영업과의 차이는?' },
{ question: '친구 몇 명있나?' },
{ question: '조직생활과 개인생활의 우선순위는?' },
{ question: '자신을 표현할 수 있는 단어를 말해보라.' },
{ question: '타인과 의견충돌시 어떻게 대처?' },
{ question: '[석사] 대학원 진학한 이유는?' },
{ question: '인턴한 회사에도 입사지원했는가? / 왜 가지않는가?' },
{ question: '블루오션을 설명해보라.' },
{ question: '[생산] 교대근무 가능한가?' },
{ question: '[서비스] 서비스란 무엇인가?' },
{ question: '당사가 성장.발전하려면?' },
{ question: '아르바이트 중 가장 힘들었던 점은?' },
{ question: '서브프라임에 대해 설명해보라.' },
{ question: '오늘 입은 옷이나 넥타이 선택이유를 말해보라.' },
{ question: '당사 매출액은?' },
{ question: '지원분야에 관련된 수강과목은?' },
{ question: '당사 비노조 문화에 대한 견해는?' },
{ question: '한국경제에 대한 견해는?' },
{ question: '해외경험이 없는 이유는?' },
{ question: '리더로서 갖추어야할 자질은?' },
{ question: '과정결과 어느것이 중요한가?' },
{ question: '가장 힘들었던 전공과목은?' },
{ question: '[영업여성] 여성인데 영업 힘들지 않겠는가?' },
{ question: '당사 문제점과 개선해야 될 점은 무엇인가?' },
{ question: '유비쿼터스란?' },
{ question: '계획을 세워 추진해본 경험은?' },
{ question: '입사후 어느 자리까지 올라가고 싶은가?' },
{ question: '면접보러 회사에 들어오면서 느낀 점은?' },
{ question: '1억이 있다면 어떻게 사용하겠는가?' },
{ question: '리더십 있는 편인가?' },
{ question: '도전해본 경험을 말해보라.' },
{ question: '우연히 돈을 주웠다면?' },
{ question: '가장 기억에 남는 여행지 / 나라는?' },
{ question: '자신의 배우자상은?' },
{ question: '주도하는 편인가  따라가는 편인가?' },
{ question: '이메일 ID가 특이한데 왜 그렇게 만들었나?' },
{ question: '군 제대후 뭐했나?' },
{ question: '팀활동에서 일어난 갈등을 해결한 경험은?' },
{ question: '경험없는 어려운 일을 맡았다면?' },
{ question: '장기자랑 해보세요' },
{ question: '단체생활 / 조직활동 경험있는가?' },
{ question: '방금한 말을 영어로 해보세요.' },
{ question: '자신의 특기를 직접 보여주세요.' },
{ question: '회사 매출증대 방안은?' },
{ question: '가훈은 무엇인가?' },
{ question: '입사후 자기개발 계획은?' },
{ question: '직장내 성희롱에 대한 견해는?' },
{ question: '인간관계에서 중요한 것은?' },
{ question: '영어회화실력은 어느정도?' },
{ question: '[여성] 잔심부름이 주어진다면?' },
{ question: '남을 설득시킨 경험있는가?' },
{ question: '한국 저출산에 대한 견해 / 대책은?' },
{ question: '자신의 고향을 소개해보라.' },
{ question: '팀을 이루어 일을 해본 경험을 말해보라.' },
{ question: '좋아하는 노래는?' },
{ question: '나이어린 선배사원이 있다면 어떻게 대할 것인가?' },
{ question: '우리 면접관들을 웃겨보라.' },
{ question: '당사 인재상은? / 인재상과 잘맞는 자신의 사례를 말해보..' },
{ question: '체력관리는 어떻게 하나?' },
{ question: '로또에 당첨된다면?' },
{ question: '프로젝트시 자신의 역할은?' },
{ question: '아이디어를 내본 경험은?' },
{ question: '입사후 진학할 생각이 있는가?' },
{ question: '상사의 부정행위 를 알게 되었다면?' },
{ question: '신불자에 대한 견해는? / 구제대책은?' },
{ question: '영어로 자신의 해외경험을 말해보라.' },
{ question: '높은 목표를 세워 일을 수행해본 경험있는가?' },
{ question: '평소 책을 많이 읽는 편인가?' },
{ question: '고객이 억지를 부리며 불합리한 요구를 한다면?' },
{ question: '용돈은 얼마나 씁니까?' },
{ question: '성장과정을 말해보라.' },
{ question: '자신이 인사담당자 / 경영자라면 채용기준은?' },
{ question: '무인도에서 필요한 3가지는? / 무인도에서 살아갈 계획.' },
{ question: '[영업] 당사 업종영업은 어떤 일을 하는지 아는가?' },
{ question: '[영업] 당사제품에 별 관심없는 고객을 어떻게 설득할 것..' },
{ question: '당사관련 기사를 읽은 적있나?' },
{ question: '윤리경영에 대한 견해는?' },
{ question: '10억이 갑자기 생긴다면?' },
{ question: '해외연수국가 선택사유는?' },
{ question: '나이가 많은 이유는?' },
{ question: '[금융] 자본시장법에 대한 견해를 말해보라.' },
{ question: '비정규직 근로자에 대한 견해 / 해결방안은?' },
{ question: '신입사원이 갖추어야할 자질.덕목은?' },
{ question: '[마케팅영업] 4P란 무엇인가?' },
{ question: '[영업금융] 자신이 상품이라고 가정하고 판매해보라.' },
{ question: '[영업] 영업관리란?' },
{ question: '다른직무도 할 수 있나?' },
{ question: '당사 제품을 당장 팔아야 한다면 어떻게 팔겠는가?' },
{ question: '내일 지구가 멸망한다면 오늘 뭘하고 싶은가?' },
{ question: '공무원 / 공기업 노조에 대한 견해는?' },
{ question: '노래할 수 있습니까?' },
{ question: '당사 핵심가치에 대해 말해보라.' },
{ question: '신상품 아이디어를 낸다면?' },
{ question: '지원분야외 관심분야는?' },
{ question: '맨홀 뚜껑이 둥근 이유는?' },
{ question: '해외경험에서 기억에 남는 것은?' },
{ question: '건강은 어떤 편인가?' },
{ question: '최근 귀하의 관심사는?' },
{ question: '독도문제에 대한 견해는?' },
{ question: '성형수술에 대한 견해는?' },
{ question: '학창시절 보람 / 성취감을 느꼈던 일은?' },
{ question: '우리그룹에 대해 아는대로 말해보라.' },
{ question: '마케팅과 영업의 차이는?' },
{ question: '당사제품의 문제점 및 개선방안을 말해보라.' },
{ question: '우리회사에 대해 어떻게 생각하나?' },
{ question: '이공계 기피현상의 이유와 대책은?' },
{ question: '부모님 성함을 한자로 써보세요.' },
{ question: '회사 사업구성에 대해 설명' },
{ question: '즐겨보는 TV프로그램은?' },
{ question: 'CRM이란? / 자신만의 CRM아이디어은?' },
{ question: '최근 신문기사 중 경제면에서의 이슈는?' },
{ question: '영어로 입사후 포부를 말해보라.' },
{ question: '전교조에 대한 견해는?' },
{ question: '한국 경제의 문제점은?' },
{ question: '당사 업종에서 일해본 경험은?' },
{ question: '면접끝나고 뭐할건가?' },
{ question: '노무현 대통령에 대한 견해는?' },
{ question: '자격증이 회사에 어떻게 도움되나?' },
{ question: '자신의 일어실력은?' },
{ question: '회사와 개인의 추구하는 가치가 다르다면?' },
{ question: '[증권] CMA란?' },
{ question: '하이브리드에 대해 설명' },
{ question: '동북공정에 대한 견해는?' },
{ question: '실패 경험이 있나?' },
{ question: '오늘 오는데 힘들지 않았나?' },
{ question: '지원분야에 아는사람있는가?' },
{ question: '특기가 자료 정리하기라고?' },
{ question: '당사 홈페이지에 대한 생각은?' },
{ question: '이번 면접에서 불합격된다면?' },
{ question: '고객 클레임 처리방안을 말해보라.' },
{ question: '평소 자신의 성격은 어떠한가?' },
{ question: '자신이 가지고 있는 역량은?' },
{ question: '상대방이 술을 과하게 권한다면?' },
{ question: '한국이 시급히 해결해야할 문제는?' },
{ question: '돈, 명예, 일 중 중요한 것은?' },
{ question: '영어로 가족소개' },
{ question: '자신의 혈액형은?' },
{ question: '고객이란?' },
{ question: '당사 제품이나 급식을 접해보았는가? 어떤가?' },
{ question: '블루오션을 당사업종에 적용한다면?' },
{ question: '리더로서 동아리활동 경험있는가?' },
{ question: '아르바이트 중 가장 기억에 남는 것은?' },
{ question: '회사 신사업 설명해보세요.' },
{ question: '[여성] 남편이 귀하의 직장생활을 반대한다면?' },
{ question: '기업의 사회적 역할은?' },
{ question: '휴학했나? 왜했나?' },
{ question: '코트라 지원했다고 했는데 탈락하고 포기했나? 다시 또 도전할건가? 왜 떨어졌다 생각하나?' },
{ question: '20년후 자신의 모습은?' },
{ question: '전문가가 되기 위한 계획은?' },
{ question: '살면서 가장 힘들었던 것은?' },
{ question: '여러사람앞에서 발표한 경험 많은가?' },
{ question: '주5일제에 대한 견해는?' },
{ question: '인생의 가치관을 바꿀 계기있었나?' },
{ question: '취업을 위해 준비한 것은?' },
{ question: '술자리에서 주량보다 더 마셔야 한다면?' },
{ question: '자신이 창의적인가?' },
{ question: '자신의 이상형은?' },
{ question: '협상에서 가장 중요한 것은?' },
{ question: '부하사원이 말을 듣지 않는다면?' },
{ question: '자신의 가치를 돈으로 환산해보라.' },
{ question: '자신의 가치관이 무엇인지 말하고 그 가치관을 가장 잘 드러낼 수 있는 사례를 말해보라.' }])
